# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/bus_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yr.rpc import common_pb2 as rpc_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc/bus_service.proto',
  package='bus_service',
  syntax='proto3',
  serialized_options=b'Z\017grpc/pb/bus;bus',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15rpc/bus_service.proto\x12\x0b\x62us_service\x1a\x10rpc/common.proto\"L\n\x15\x44iscoverDriverRequest\x12\x10\n\x08\x64riverIP\x18\x01 \x01(\t\x12\x12\n\ndriverPort\x18\x02 \x01(\t\x12\r\n\x05jobID\x18\x03 \x01(\t\"\x18\n\x16\x44iscoverDriverResponse\"C\n\x17\x44iscoverFrontendRequest\x12\x12\n\nfrontendIP\x18\x01 \x01(\t\x12\x14\n\x0c\x66rontendPort\x18\x02 \x01(\t\"\x1a\n\x18\x44iscoverFrontendResponse\"*\n\x14QueryInstanceRequest\x12\x12\n\ninstanceID\x18\x01 \x01(\t\"Y\n\x15QueryInstanceResponse\x12\x1f\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x11.common.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2\xa6\x02\n\nBusService\x12\x61\n\x10\x44iscoverFrontend\x12$.bus_service.DiscoverFrontendRequest\x1a%.bus_service.DiscoverFrontendResponse\"\x00\x12X\n\rQueryInstance\x12!.bus_service.QueryInstanceRequest\x1a\".bus_service.QueryInstanceResponse\"\x00\x12[\n\x0e\x44iscoverDriver\x12\".bus_service.DiscoverDriverRequest\x1a#.bus_service.DiscoverDriverResponse\"\x00\x42\x11Z\x0fgrpc/pb/bus;busb\x06proto3'
  ,
  dependencies=[rpc_dot_common__pb2.DESCRIPTOR,])




_DISCOVERDRIVERREQUEST = _descriptor.Descriptor(
  name='DiscoverDriverRequest',
  full_name='bus_service.DiscoverDriverRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='driverIP', full_name='bus_service.DiscoverDriverRequest.driverIP', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='driverPort', full_name='bus_service.DiscoverDriverRequest.driverPort', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jobID', full_name='bus_service.DiscoverDriverRequest.jobID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=132,
)


_DISCOVERDRIVERRESPONSE = _descriptor.Descriptor(
  name='DiscoverDriverResponse',
  full_name='bus_service.DiscoverDriverResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=158,
)


_DISCOVERFRONTENDREQUEST = _descriptor.Descriptor(
  name='DiscoverFrontendRequest',
  full_name='bus_service.DiscoverFrontendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frontendIP', full_name='bus_service.DiscoverFrontendRequest.frontendIP', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frontendPort', full_name='bus_service.DiscoverFrontendRequest.frontendPort', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=227,
)


_DISCOVERFRONTENDRESPONSE = _descriptor.Descriptor(
  name='DiscoverFrontendResponse',
  full_name='bus_service.DiscoverFrontendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=255,
)


_QUERYINSTANCEREQUEST = _descriptor.Descriptor(
  name='QueryInstanceRequest',
  full_name='bus_service.QueryInstanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceID', full_name='bus_service.QueryInstanceRequest.instanceID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=299,
)


_QUERYINSTANCERESPONSE = _descriptor.Descriptor(
  name='QueryInstanceResponse',
  full_name='bus_service.QueryInstanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='bus_service.QueryInstanceResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='bus_service.QueryInstanceResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='bus_service.QueryInstanceResponse.status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=390,
)

_QUERYINSTANCERESPONSE.fields_by_name['code'].enum_type = rpc_dot_common__pb2._ERRORCODE
DESCRIPTOR.message_types_by_name['DiscoverDriverRequest'] = _DISCOVERDRIVERREQUEST
DESCRIPTOR.message_types_by_name['DiscoverDriverResponse'] = _DISCOVERDRIVERRESPONSE
DESCRIPTOR.message_types_by_name['DiscoverFrontendRequest'] = _DISCOVERFRONTENDREQUEST
DESCRIPTOR.message_types_by_name['DiscoverFrontendResponse'] = _DISCOVERFRONTENDRESPONSE
DESCRIPTOR.message_types_by_name['QueryInstanceRequest'] = _QUERYINSTANCEREQUEST
DESCRIPTOR.message_types_by_name['QueryInstanceResponse'] = _QUERYINSTANCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiscoverDriverRequest = _reflection.GeneratedProtocolMessageType('DiscoverDriverRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCOVERDRIVERREQUEST,
  '__module__' : 'rpc.bus_service_pb2'
  # @@protoc_insertion_point(class_scope:bus_service.DiscoverDriverRequest)
  })
_sym_db.RegisterMessage(DiscoverDriverRequest)

DiscoverDriverResponse = _reflection.GeneratedProtocolMessageType('DiscoverDriverResponse', (_message.Message,), {
  'DESCRIPTOR' : _DISCOVERDRIVERRESPONSE,
  '__module__' : 'rpc.bus_service_pb2'
  # @@protoc_insertion_point(class_scope:bus_service.DiscoverDriverResponse)
  })
_sym_db.RegisterMessage(DiscoverDriverResponse)

DiscoverFrontendRequest = _reflection.GeneratedProtocolMessageType('DiscoverFrontendRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCOVERFRONTENDREQUEST,
  '__module__' : 'rpc.bus_service_pb2'
  # @@protoc_insertion_point(class_scope:bus_service.DiscoverFrontendRequest)
  })
_sym_db.RegisterMessage(DiscoverFrontendRequest)

DiscoverFrontendResponse = _reflection.GeneratedProtocolMessageType('DiscoverFrontendResponse', (_message.Message,), {
  'DESCRIPTOR' : _DISCOVERFRONTENDRESPONSE,
  '__module__' : 'rpc.bus_service_pb2'
  # @@protoc_insertion_point(class_scope:bus_service.DiscoverFrontendResponse)
  })
_sym_db.RegisterMessage(DiscoverFrontendResponse)

QueryInstanceRequest = _reflection.GeneratedProtocolMessageType('QueryInstanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYINSTANCEREQUEST,
  '__module__' : 'rpc.bus_service_pb2'
  # @@protoc_insertion_point(class_scope:bus_service.QueryInstanceRequest)
  })
_sym_db.RegisterMessage(QueryInstanceRequest)

QueryInstanceResponse = _reflection.GeneratedProtocolMessageType('QueryInstanceResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYINSTANCERESPONSE,
  '__module__' : 'rpc.bus_service_pb2'
  # @@protoc_insertion_point(class_scope:bus_service.QueryInstanceResponse)
  })
_sym_db.RegisterMessage(QueryInstanceResponse)


DESCRIPTOR._options = None

_BUSSERVICE = _descriptor.ServiceDescriptor(
  name='BusService',
  full_name='bus_service.BusService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=393,
  serialized_end=687,
  methods=[
  _descriptor.MethodDescriptor(
    name='DiscoverFrontend',
    full_name='bus_service.BusService.DiscoverFrontend',
    index=0,
    containing_service=None,
    input_type=_DISCOVERFRONTENDREQUEST,
    output_type=_DISCOVERFRONTENDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryInstance',
    full_name='bus_service.BusService.QueryInstance',
    index=1,
    containing_service=None,
    input_type=_QUERYINSTANCEREQUEST,
    output_type=_QUERYINSTANCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DiscoverDriver',
    full_name='bus_service.BusService.DiscoverDriver',
    index=2,
    containing_service=None,
    input_type=_DISCOVERDRIVERREQUEST,
    output_type=_DISCOVERDRIVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUSSERVICE)

DESCRIPTOR.services_by_name['BusService'] = _BUSSERVICE

# @@protoc_insertion_point(module_scope)
