# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc/common.proto',
  package='common',
  syntax='proto3',
  serialized_options=b'Z\027bus/proto/common;common',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10rpc/common.proto\x12\x06\x63ommon\"r\n\x03\x41rg\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.common.Arg.ArgType\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x13\n\x0bnested_refs\x18\x03 \x03(\t\"$\n\x07\x41rgType\x12\t\n\x05VALUE\x10\x00\x12\x0e\n\nOBJECT_REF\x10\x01*\xc4\x02\n\tErrorCode\x12\x0c\n\x08\x45RR_NONE\x10\x00\x12\x16\n\x11\x45RR_PARAM_INVALID\x10\xe9\x07\x12\x1c\n\x17\x45RR_RESOURCE_NOT_ENOUGH\x10\xea\x07\x12\x1b\n\x16\x45RR_INSTANCE_NOT_FOUND\x10\xeb\x07\x12\x1c\n\x17\x45RR_INSTANCE_DUPLICATED\x10\xec\x07\x12\x1c\n\x17\x45RR_INVOKE_RATE_LIMITED\x10\xed\x07\x12\x17\n\x12\x45RR_USER_CODE_LOAD\x10\xd1\x0f\x12 \n\x1b\x45RR_USER_FUNCTION_EXCEPTION\x10\xd2\x0f\x12$\n\x1f\x45RR_REQUEST_BETWEEN_RUNTIME_BUS\x10\xb9\x17\x12\x1c\n\x17\x45RR_INNER_COMMUNICATION\x10\xba\x17\x12\x1b\n\x16\x45RR_INNER_SYSTEM_ERROR\x10\xbb\x17\x42\x19Z\x17\x62us/proto/common;commonb\x06proto3'
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='common.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERR_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERR_PARAM_INVALID', index=1, number=1001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERR_RESOURCE_NOT_ENOUGH', index=2, number=1002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERR_INSTANCE_NOT_FOUND', index=3, number=1003,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERR_INSTANCE_DUPLICATED', index=4, number=1004,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERR_INVOKE_RATE_LIMITED', index=5, number=1005,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERR_USER_CODE_LOAD', index=6, number=2001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERR_USER_FUNCTION_EXCEPTION', index=7, number=2002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERR_REQUEST_BETWEEN_RUNTIME_BUS', index=8, number=3001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERR_INNER_COMMUNICATION', index=9, number=3002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERR_INNER_SYSTEM_ERROR', index=10, number=3003,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=145,
  serialized_end=469,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
ERR_NONE = 0
ERR_PARAM_INVALID = 1001
ERR_RESOURCE_NOT_ENOUGH = 1002
ERR_INSTANCE_NOT_FOUND = 1003
ERR_INSTANCE_DUPLICATED = 1004
ERR_INVOKE_RATE_LIMITED = 1005
ERR_USER_CODE_LOAD = 2001
ERR_USER_FUNCTION_EXCEPTION = 2002
ERR_REQUEST_BETWEEN_RUNTIME_BUS = 3001
ERR_INNER_COMMUNICATION = 3002
ERR_INNER_SYSTEM_ERROR = 3003


_ARG_ARGTYPE = _descriptor.EnumDescriptor(
  name='ArgType',
  full_name='common.Arg.ArgType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VALUE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OBJECT_REF', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=106,
  serialized_end=142,
)
_sym_db.RegisterEnumDescriptor(_ARG_ARGTYPE)


_ARG = _descriptor.Descriptor(
  name='Arg',
  full_name='common.Arg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='common.Arg.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='common.Arg.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nested_refs', full_name='common.Arg.nested_refs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ARG_ARGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=142,
)

_ARG.fields_by_name['type'].enum_type = _ARG_ARGTYPE
_ARG_ARGTYPE.containing_type = _ARG
DESCRIPTOR.message_types_by_name['Arg'] = _ARG
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Arg = _reflection.GeneratedProtocolMessageType('Arg', (_message.Message,), {
  'DESCRIPTOR' : _ARG,
  '__module__' : 'rpc.common_pb2'
  # @@protoc_insertion_point(class_scope:common.Arg)
  })
_sym_db.RegisterMessage(Arg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
