# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from yr.rpc import runtime_rpc_pb2 as rpc_dot_runtime__rpc__pb2


class RuntimeRPCStub(object):
    """RuntimeRPC provide bidirectional streaming RPC interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MessageStream = channel.stream_stream(
                '/runtime_rpc.RuntimeRPC/MessageStream',
                request_serializer=rpc_dot_runtime__rpc__pb2.StreamingMessage.SerializeToString,
                response_deserializer=rpc_dot_runtime__rpc__pb2.StreamingMessage.FromString,
                )


class RuntimeRPCServicer(object):
    """RuntimeRPC provide bidirectional streaming RPC interface
    """

    def MessageStream(self, request_iterator, context):
        """build bidirection grpc communication channel, different message body type specify different api handler
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MessageStream': grpc.stream_stream_rpc_method_handler(
                    servicer.MessageStream,
                    request_deserializer=rpc_dot_runtime__rpc__pb2.StreamingMessage.FromString,
                    response_serializer=rpc_dot_runtime__rpc__pb2.StreamingMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtime_rpc.RuntimeRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RuntimeRPC(object):
    """RuntimeRPC provide bidirectional streaming RPC interface
    """

    @staticmethod
    def MessageStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/runtime_rpc.RuntimeRPC/MessageStream',
            rpc_dot_runtime__rpc__pb2.StreamingMessage.SerializeToString,
            rpc_dot_runtime__rpc__pb2.StreamingMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
